package com.br.sisgetrim.model.enums;

public enum AtribuicaoCartorio {
    NOTAS,
    PROTESTO_DE_TITULOS,
    REGISTRO_CIVIL_DAS_PESSOAS_JURIDICAS,
    REGISTRO_CIVIL_DAS_PESSOAS_NATURAIS_E_DE_INTERDICAO_E_TUTELAS,
    REGISTRO_DE_CONTRATOS_MARITIMOS,
    REGISTRO_DE_DISTRIBUICAO,
    REGISTRO_DE_IMOVEIS;
}
