CREATE TABLE entidades (
    id SERIAL PRIMARY KEY,
    cnpj VARCHAR(18) UNIQUE NOT NULL,
    tipo_estabelecimento VARCHAR(20),
    data_abertura DATE,
    nome_empresarial VARCHAR(255) NOT NULL,
    nome_fantasia VARCHAR(255),
    porte VARCHAR(50),
    cnae_principal VARCHAR(255),
    cnae_secundario TEXT,
    natureza_juridica VARCHAR(255),
    logradouro VARCHAR(255),
    numero VARCHAR(20),
    complemento VARCHAR(255),
    cep VARCHAR(10),
    bairro VARCHAR(100),
    municipio VARCHAR(100),
    uf CHAR(2),
    email VARCHAR(255),
    telefone VARCHAR(20),
    ente_federativo VARCHAR(255),
    situacao_cadastral VARCHAR(50),
    data_situacao_cadastral DATE,
    motivo_situacao_cadastral TEXT,
    situacao_especial VARCHAR(100),
    data_situacao_especial DATE,
    logo_url VARCHAR(255),
    ativo BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
